config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    member do
      post :reprocess
    end
  end

  resources :short_links, only: :show, path: :s

  root to: 'users#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/user_constants.rb
# frozen_string_literal: true

module UserConstants
  PENDING_STATE = :pending
  PROCESSING_STATE = :processing
  COMPLETED_STATE = :completed
  FAILED_STATE = :failed
  SEARCH_COLUMNS = %w[name github_name location organization].freeze
end

app/models/short_code.rb
# frozen_string_literal: false

module ShortCode
  ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.freeze
  BASE = ALPHABET.length
  ALPHABET_HASH = Hash[ALPHABET.chars.zip(0..BASE)]

  def self.encode(num = 0)
    return ALPHABET[num] if num.zero?

    result = ''

    while num.positive?
      result = (ALPHABET[num % BASE]) + result
      num /= BASE
    end

    result
  end

  def self.decode(str)
    number = 0

    str.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET_HASH[char]
      number += index * power
    end

    number
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :skip_callbacks

  include UserConstants

  validates :name, presence: true, length: { maximum: 25 }
  validates :github_url, presence: true, length: { maximum: 50 }, format: { with: %r{https://github\.com/[\w-]+} }, uniqueness: { case_sensitive: true }

  encrypts :github_url, deterministic: true, downcase: true

  after_create :start_processing!, unless: :skip_callbacks

  scope :search_by_term, lambda { |term|
    query = SEARCH_COLUMNS.map { |column| "#{column} ILIKE :term" }.join(' OR ')
    where(query, term: "%#{term}%")
  }

  state_machine :state, initial: :pending do
    state PENDING_STATE
    state PROCESSING_STATE
    state COMPLETED_STATE
    state FAILED_STATE

    event :start_processing do
      transition pending: :processing
    end

    event :reprocess do
      transition all - [:pending] => :processing
    end

    after_transition to: :processing, do: :enqueue_processing_job
  end

  private

  def enqueue_processing_job
    GithubScraperJob.perform_later(id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/short_links_controller.rb
# frozen_string_literal: true

class ShortLinksController < ApplicationController
  before_action :set_user, only: :show

  def show
    redirect_to @user.github_url, allow_other_host: true
  end

  private

  def set_user
    @user = User.find_by!(unique_identifier:)
  end

  def unique_identifier
    ShortCode.decode(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy reprocess]

  # GET /users or /users.json
  def index
    @users = fetch_users(params[:query])
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reprocess
    @user.reprocess!

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Reprocessing in progress, check back shortly for updated details.' }
      format.json { head :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :github_url)
  end

  def fetch_users(term)
    return User.all unless term.present?

    User.search_by_term(term)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/short_links_helper.rb
# frozen_string_literal: true

module ShortLinksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def shortened_github_url(user)
    Rails.application.config.url + "/s/#{ShortCode.encode(user.unique_identifier)}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubProfiles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-16 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label "Name:" %>
    <%= form.text_field :name, required: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Github URL:" %>
    <%= form.url_field :github_url, required: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_unprocessed_user.html.erb
<div id="<%= dom_id @user %>" class="max-w-md mb-5 mx-auto bg-white shadow-md rounded-lg overflow-hidden">
  <div class="relative">
    <div class="h-16 bg-gray-600"></div>
  </div>

  <div class="text-center mb-6 mt-4 px-6">
    <h2 class="text-xl font-bold text-gray-900"><%= @user.name %></h2>
    <p class="text-gray-600 text-sm">@<%= @user.github_url[GithubScraper::USERNAME_REGEXP] %></p>
    <p class="text-blue-500 text-sm">
      <a href="<%= shortened_github_url(@user) %>" target="_blank" class="hover:underline"><%= shortened_github_url(@user) %></a>
    </p>
  </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="max-w-md mb-5 mx-auto bg-white shadow-md rounded-lg overflow-hidden">
  <div class="relative">
    <div class="h-32 bg-blue-600"></div>

    <div class="absolute top-20 left-1/2 transform -translate-x-1/2">
      <img class="h-24 w-24 rounded-full border-4 border-white object-cover" src="<%= user.profile_image_url %>" alt="<%= user.name %>">
    </div>
  </div>

  <div class="text-center mb-4 mt-16 px-6">
    <h2 class="text-xl font-bold text-gray-900"><%= user.name %></h2>
    <p class="text-gray-600 text-sm">@<%= user.github_name %></p>
    <p class="text-blue-500 text-sm"><a href="<%= shortened_github_url(user) %>" target="_blank" class="hover:underline"><%= shortened_github_url(user) %></a></p>
  </div>

  <div class="flex justify-around px-6 py-4 border-t border-gray-200">
    <div class="text-center">
      <p class="text-gray-800 font-semibold"><%= user.followers %></p>
      <p class="text-gray-600 text-sm">Followers</p>
    </div>
    <div class="text-center">
      <p class="text-gray-800 font-semibold"><%= user.following %></p>
      <p class="text-gray-600 text-sm">Following</p>
    </div>
    <div class="text-center">
      <p class="text-gray-800 font-semibold"><%= user.stars %></p>
      <p class="text-gray-600 text-sm">Stars</p>
    </div>
  </div>

  <div class="px-6 py-4 border-t border-gray-200">
    <div class="flex items-center mt-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-600 mr-1">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
      </svg>
      <p class="text-gray-600 text-sm"><%= user.contributions_last_year %> Contributions Last Year</p>
    </div>

    <% if user.location? %>
      <div class="flex items-center mt-2">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-600 mr-1">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z" />
        </svg>
        <p class="text-gray-600 text-sm"><%= user.location %></p>
      </div>
    <% end %>

    <% if user.organization? %>
      <div class="flex items-center mt-2">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-600 mr-1">
          <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 14.15v4.25c0 1.094-.787 2.036-1.872 2.18-2.087.277-4.216.42-6.378.42s-4.291-.143-6.378-.42c-1.085-.144-1.872-1.086-1.872-2.18v-4.25m16.5 0a2.18 2.18 0 0 0 .75-1.661V8.706c0-1.081-.768-2.015-1.837-2.175a48.114 48.114 0 0 0-3.413-.387m4.5 8.006c-.194.165-.42.295-.673.38A23.978 23.978 0 0 1 12 15.75c-2.648 0-5.195-.429-7.577-1.22a2.016 2.016 0 0 1-.673-.38m0 0A2.18 2.18 0 0 1 3 12.489V8.706c0-1.081.768-2.015 1.837-2.175a48.111 48.111 0 0 1 3.413-.387m7.5 0V5.25A2.25 2.25 0 0 0 13.5 3h-3a2.25 2.25 0 0 0-2.25 2.25v.894m7.5 0a48.667 48.667 0 0 0-7.5 0M12 12.75h.008v.008H12v-.008Z" />
        </svg>
        <p class="text-gray-600 text-sm"><%= user.organization %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Users" %>

  <div class="flex justify-between items-center mb-4">
    <h1 class="font-bold text-4xl">Users</h1>

    <div class="flex items-center space-x-2">
      <%= form_with url: users_path, method: :get, local: true, class: "flex items-center" do %>
        <input type="text" name="query" placeholder="Search users..." value="<%= params[:query] %>" class="px-3 py-2 border border-gray-300 rounded-lg" />
        <button type="submit" class="ml-2 py-2 px-4 bg-blue-600 text-white rounded-lg font-medium">Search</button>
      <% end %>

      <%= link_to "New user", new_user_path, class: "py-2 px-4 bg-blue-600 text-white rounded-lg font-medium" %>
    </div>
  </div>

  <div class="overflow-x-auto mt-10">
    <table class="min-w-full bg-white border border-gray-200 rounded-lg shadow-md">
      <thead class="bg-gray-100 border-b border-gray-200">
      <tr>
        <th class="py-2 px-4 text-left text-gray-600">Name</th>
        <th class="py-2 px-4 text-left text-gray-600">GitHub URL</th>
        <th class="py-2 px-4 text-left text-gray-600">State</th>
        <th class="py-2 px-4 text-left text-gray-600">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr class="border-b border-gray-200">
          <td class="py-2 px-4 text-gray-800"><%= user.name %></td>
          <td class="py-2 px-4 text-blue-500"><a href="<%= shortened_github_url(user) %>" target="_blank" class="hover:underline"><%= shortened_github_url(user) %></a></td>
          <td class="py-2 px-4 text-gray-800"
              data-controller="state-class"
              data-state-class-state-value="<%= user.state %>">
                <span data-state-class-target="state" class="inline-block px-2 py-1 rounded-full text-xs font-semibold">
                  <%= user.state.humanize %>
                </span>
          </td>
          <td class="py-2 px-4 space-x-2">
            <%= link_to "Show", user, class: "text-blue-600 hover:text-blue-800" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex flex-col items-center">
  <div class="mb-5">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= @user.completed? ? render(@user) : render('unprocessed_user') %>

    <div class="flex flex-wrap justify-center gap-2 mt-2">
      <%= link_to "Edit this user", edit_user_path(@user), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      <%= link_to "Back to users", users_path, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      <%= button_to "Reprocess", reprocess_user_path(@user), method: :post, class: "rounded-lg py-3 px-5 bg-blue-500 text-white font-medium" %>
      <%= button_to "Destroy", @user, method: :delete, class: "rounded-lg py-3 px-5 bg-red-500 text-white font-medium" %>
    </div>
  </div>
</div>